openapi: 3.0.0
info:
  title: Omoro Deep Danbooru API
  version: 1.0.0
servers:
  - url: https://Omoron-OmoroDeepDanbooru.hf.space
paths:
  /predict:
    post:
      summary: 画像を解析し、タグ推定結果を返す
      operationId: predictTags
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: アップロードする画像ファイル
      responses:
        '200':
          description: タグ推定成功時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        tag:
                          type: string
                        score:
                          type: number
                          format: float
